# Generated by Django 2.0.7 on 2018-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_snaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_search',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
